version: "3.8"
services:
  backend:
    build:
      context: ./backend/
    volumes:
      - type: volume
        source: simple-app-volume
        target: /simple-app/backend/database/
    networks:
      - isolated-network
    ports:
      - "3000:3000"
  
  frontend:
    build:
      context: ./frontend/
    networks:
      - isolated-network
    ports:
      - "3001:3001"

# Named volume mounted using an externally created named volume
volumes:
  simple-app-volume:
    external: true

# Unlike docker run normally, docker-compose creates a default network that isn't the network with NAME="bridge"
# Specify own network name rather than use default "simple-app_default" used by docker-compose given name of cwd
# Can use external like volumes above to specify an external network
# its bridge by default. Just being verbose
# Issue: Not actually using in index.js at the moment since fetch() being called from Browser on host, not from the container hosting the frontend files. But the config still stands
networks:
  isolated-network:
    driver: bridge
